import { AppError } from "@/server/core/errors";
import { STATUS_CODE } from "@/server/core/constants";
import { AI_MESSAGES } from "@/server/services/ai/ai.constants";

const AI_ERROR_STATUS: Partial<Record<AI_MESSAGES, STATUS_CODE>> = {
  [AI_MESSAGES.RATE_LIMITED]: STATUS_CODE.TOO_MANY_REQUESTS,
  [AI_MESSAGES.PROVIDER_OVERLOADED]: STATUS_CODE.SERVICE_UNAVAILABLE,
  [AI_MESSAGES.PROVIDER_TIMEOUT]: STATUS_CODE.GATEWAY_TIMEOUT,
  [AI_MESSAGES.PROVIDER_AUTH_FAILED]: STATUS_CODE.SERVER_ERROR,
  [AI_MESSAGES.MODEL_NOT_AVAILABLE]: STATUS_CODE.SERVER_ERROR,
  [AI_MESSAGES.PROVIDER_REJECTED_REQUEST]: STATUS_CODE.SERVER_ERROR,
  [AI_MESSAGES.PROVIDER_FAILED]: STATUS_CODE.SERVER_ERROR,
};

export function toAiError(message: AI_MESSAGES, cause: unknown): AppError {
  return new AppError({
    message,
    statusCode: AI_ERROR_STATUS[message] ?? STATUS_CODE.SERVER_ERROR,
    cause,
  });
}
