import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import "@/app/styles/globals.css";

export const baloo2 = Baloo_2({
  subsets: ["latin", "vietnamese"],
  weight: ["500", "800"],
});

export const metadata: Metadata = {
  title: "Fake API",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baloo2.className} antialiased`}>{children}</body>
    </html>
  );
}
